urg_node2:
  ros__parameters:
    serial_port: '/dev/hokuyo'
    serial_baud: 115200
    frame_id : 'nav_hokuyo_laser_link' #'laser'
    calibrate_time : false
    synchronize_time : false
    publish_intensity : false
    publish_multiecho : false
    error_limit : 4
    error_reset_period : 5.0
    diagnostics_tolerance : 0.05
    diagnostics_window_time : 5.0
    time_offset : 0.0
    angle_min : -1.5
    angle_max : 1.5
    skip : 0
    cluster : 1
